import type { Metadata } from "next";
import { Figtree,DM_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { shadcn } from '@clerk/themes'
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip"
const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});
const font = DM_Sans({
  subsets:["latin"]
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <ClerkProvider
    appearance={{
        baseTheme: shadcn,
      }}
  >
      <html lang="en" >
      <body
        className={` antialiased ${font.className}`}
      >
     <TooltipProvider>
         {children}
     </TooltipProvider>
      </body>
    </html>
  </ClerkProvider>
  );
}
